import boto3

ACCESS_ID = input("Please enter the access key of AWS account : ")
ACCESS_KEY = input("Please enter the secret key of AWS account : ")
region = input("Please enter the canonical name of the region of AWS account : ")
ec2 = boto3.resource('ec2', region, aws_access_key_id=ACCESS_ID, aws_secret_access_key=ACCESS_KEY)
print("The running instance ids in your account are : ")
for instance in ec2.instances.all():
    print(instance.id)

instance_id = input("please enter the instance id you want to get metadata for : ")
ec2_client = boto3.client('ec2', 'us-east-1', aws_access_key_id=ACCESS_ID, aws_secret_access_key=ACCESS_KEY)
response = ec2_client.describe_instances(InstanceIds=[instance_id])
# print(response)
print("\nThe metadata of the selected instance is : ")
print("\nInstance Id : ", response['Reservations'][0]['Instances'][0]['InstanceId'])
print("Instance Type : ", response['Reservations'][0]['Instances'][0]['InstanceType'])
print("Key Name : ", response['Reservations'][0]['Instances'][0]['KeyName'])
print("Availability Zone : ", response['Reservations'][0]['Instances'][0]['Placement']['AvailabilityZone'])
print("Private Dns Name : ", response['Reservations'][0]['Instances'][0]['PrivateDnsName'])
print("Private Ip Address : ", response['Reservations'][0]['Instances'][0]['PrivateIpAddress'])
print("Public Dns Name : ", response['Reservations'][0]['Instances'][0]['PublicDnsName'])
print("Public Ip Address", response['Reservations'][0]['Instances'][0]['PublicIpAddress'])
print("Instance State : ", response['Reservations'][0]['Instances'][0]['State']['Name'])
print("Subnet Id : ", response['Reservations'][0]['Instances'][0]['SubnetId'])
print("Vpc Id : ", response['Reservations'][0]['Instances'][0]['VpcId'])
print("MacAddress : ", response['Reservations'][0]['Instances'][0]['NetworkInterfaces'][0]['MacAddress'])
print("Network Interface Id", response['Reservations'][0]['Instances'][0]['NetworkInterfaces'][0]['NetworkInterfaceId'])
print("Security Group Id : ", response['Reservations'][0]['Instances'][0]['SecurityGroups'][0]['GroupId'])
